#!/bin/bash
mkdir -p ../../app

appPath="../../app/app.js"
touch $appPath
echo "" > $appPath

cssPath="../../app/app.css"
touch $cssPath
echo "" > $cssPath

echo -e "\n" >> $appPath; cat ../script/_base/Navigation.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/_base/Navigation.Prj.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/_base/choseong.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/_base/common_.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/_base/commonEvent.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/_base/CommonEvent.Prj.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/_base/GGdate.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/_base/GGdialog.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/_base/GGhtml.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/_base/GGpage.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/_base/GGslideform.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/_base/GGtoast.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/_base/GGutils.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/_base/GGvalid/GGvalid.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/_base/GGvalid/GGvalid-api.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/_base/GGvalid/GGvalid-common.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/_base/GGvalid/GGvalid-user.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/_base/GGC/GGC.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/_base/GGC/GGC-all.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/_base/GGC/GGC-cls.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/_base/GGC/GGC-clslineupb.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/_base/GGC/GGC-clspurchasehist.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/_base/GGC/GGC-clssettle.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/_base/GGC/GGC-clssettlehist.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/_base/GGC/GGC-date.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/_base/GGC/GGC-grp.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/_base/GGC/GGC-GrpMember.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/_base/GGC/GGC-GrpfncSponsorship.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/_base/GGC/GGC-user.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/_base/api.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/_base/api-pr.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-ref/api-govAddr.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-ref/api-systemBoard.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-pr/ApiPr-addrcode.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/api-addressSido.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/api-addrcode.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/api-addressSigungu.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/api-bank.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/api-bankaccount.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/api-cls.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/api-clslineupa.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/api-clslineupb.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/api-clslineuptmpa.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/api-clslineuptmpb.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/api-clslineuptmpc.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/api-clspurchase.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/api-clspurchasehist.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/api-clssettle.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/api-clssettlehist.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/api-clssettletmp.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/api-grp.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/api-grpIntro.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/api-userAddr.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/Api.GrpfncLoss.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/api-GrpfncPurchase.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/api-GrpfncSponsorship.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/api-Grpfnca.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/api-Grpfnclog.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/api-grpmtaga.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/api-grpmtagb.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/api-grpMember.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/api-grpMemberPointhist.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/api-systemBoard.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/api-user.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/Api.Scheduleall.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/api/api-table/Api.Schedulebyweek.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-common/_MCommon.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-common/MApiResponse.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-ref/MAddressSido.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-ref/MAddrcode.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-ref/MAddressSigungu.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-ref/MBank.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-ref/MGovAddr.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-table/MBankaccount.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-table/MCls.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-table/MClslineupa.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-table/MClslineupb.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-table/MClslineuptmpa.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-table/MClslineuptmpb.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-table/MClslineuptmpc.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-table/MClspurchase.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-table/MClspurchasehist.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-table/MClssettle.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-table/MClssettlehist.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-table/MClssettletmp.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-table/MGrp.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-table/MGrpIntro.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-table/MUserAddr.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-table/MGrpfncLoss.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-table/MGrpfncPurchase.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-table/MGrpfncSponsorship.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-table/MGrpfnca.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-table/MGrpfnclog.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-table/MGrpmtaga.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-table/MGrpmtagb.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-table/MGrpMember.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-table/MGrpMemberPointhist.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-table/MSystemBoard.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-table/MUser.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-table/MScheduleall.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-table/MSchedulebyweek.js >> $appPath
echo -e "\n" >> $appPath; cat ../script/model/model-table/MSchedulebytime.js >> $appPath


echo -e "\n" >> $cssPath; cat ../css/common/css/common.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/common/css/common-btn.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/common/css/common-div.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/common/css/common-div-checkbox.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/common/css/common-div-dialog.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/common/css/common-hr.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/common/css/common-img.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/common/css/common-input.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/common/css/common-checkbox.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/common/css/common-p.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/common/css/common-radio.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/common/css/common-search.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/common/css/common-select.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/common/css/common-span.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/common/css/common-switch.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/common/css/common-tag.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/common/css/common-tbl.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/common/css/common-ul.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/common/css/common-tabbar.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/common-event/common-event.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/page/css/page.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/page/css/index.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/page/css/A00UserLogin.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/model/css/MUser.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/entity/css/entity.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/entity/css/entity-common.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/entity/css/entity-MBank.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/entity/css/entity-MGovAddr.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/entity/css/entity-MSystemBoard.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/entity/css/entity-MBankaccount.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/entity/css/entity-MCls.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/entity/css/entity-MClssettlehist.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/entity/css/entity-MClspurchasehist.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/entity/css/entity-MGrp.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/entity/css/entity-MGrpfncLoss.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/entity/css/entity-MGrpfncPurchase.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/entity/css/entity-MGrpfncSponsorship.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/entity/css/entity-MSchedulebyweek.css >> $cssPath
echo -e "\n" >> $cssPath; cat ../css/entity/css/entity-MAddrcode.css >> $cssPath
